### ISSUE TITLE
Irregular spacing between ocr pages

### ISSUE THREAD

**Issue by dwemhoen** [CIIR/Proteus#103]
When I click the "next page" button in the OCR view, sometimes the next page will appear right below the current one, while other times there will be a page-sized blank space between them.

**Comment by mzarozinski** [comment]
Fixed in:

Branch: refs/heads/tagging
Home: https://github.com/CIIR/Proteus
Commit: b1f840f
b1f840f
Author: mzarozinski MichaelZ@cs.umass.edu
Date: 2016-05-13 (Fri, 13 May 2016)
