### ISSUE TITLE
Some OCR views need to be wider

### ISSUE THREAD

**Issue by jjfiv** [CIIR/Proteus#106]
http://laguna.cs.umass.edu:2335/view.html?kind=ia-pages&action=view&id=atlastachristma02kinggoog_321&queryid=42

There's plenty of room on my monitor, but every line wraps.

**Comment by mzarozinski** [comment]
Improved OCR view in:

Branch: refs/heads/tagging
  Home:   https://github.com/CIIR/Proteus
  Commit: b1f840f9f9d34a84865e854112bbc921500a6823
      https://github.com/CIIR/Proteus/commit/b1f840f9f9d34a84865e854112bbc921500a6823
  Author: mzarozinski <MichaelZ@cs.umass.edu>
  Date:   2016-05-13 (Fri, 13 May 2016)
