### ISSUE TITLE
Bug in duplication

### ISSUE THREAD

**Issue by boomz** [CIIR/Proteus#107]
When I selected "All" to search and issue the "states" query. The system retrieve just one result, with 9 duplications. 
Issue 1: I am not sure it's a bug or not, but there are lots of "transmitting states" in the description of the search result. I believe it doesn't make sense to repeat such a thing a million times!

Issue 2: Do this: click on duplications to expand them. Then scroll down to load more duplications. Now go up and hide duplications. Now the results will change from 1 to much more! and all of them seem to be duplicate!

**Comment by mzarozinski** [comment]
This is the "correct" behavior - for now - n the future we'd like to filter out these "junk" pages.

**Comment by j-allan** [comment]
I disagree that this behavior is correct.

When I run the query “states” I get one result and a claim that there are 9 duplicates. It also maintains the “Search request sent to server!” notification on the bottom of the list.

When I click “show duplicate” and then scroll down, only the first eight are showed. Then it expands and adds more. Far more than just one more. It also adds a number of non-duplicates in the list (though they look very similar). When I scroll down to the bottom of that list it loads more. Recall that *ONE* item was shown to start with; now there are many.

At this point, if I scroll back up to the top and click “hide duplicates” it collapses them and says there are 24.

The numbers are changing and are not consistent. This behavior is not correct.
