### ISSUE TITLE
Highlight the query terms in view OCR?

### ISSUE THREAD

**Issue by jiepujiang** [CIIR/Proteus#110]
When I searched something and clicked on the "view OCR" link for a result, the view OCR page did not highlight the query terms for me.

**Comment by mzarozinski** [comment]
Fixed in:

Branch: refs/heads/tagging
  Home:   https://github.com/CIIR/Proteus
  Commit: b1f840f9f9d34a84865e854112bbc921500a6823
      https://github.com/CIIR/Proteus/commit/b1f840f9f9d34a84865e854112bbc921500a6823
  Author: mzarozinski <MichaelZ@cs.umass.edu>
  Date:   2016-05-13 (Fri, 13 May 2016)

Note, books don't currently highlight terms.
