### ISSUE TITLE
Quoted Labels Don't Show Up

### ISSUE THREAD

**Issue by dwemhoen** [CIIR/Proteus#20]
After creating a new label/value and submitting it, the label doesn't show up on the left-hand column, and the label/value pair attached to that result vanishes after I make another search.

**Comment by mzarozinski** [comment]
this is most likely because the "add a label" box is still there when you log out, they should be disabled upon logout.

**Comment by dwemhoen** [comment]
Additional Note: I'm seeing this error in Firefox on both Linux and Windows 7

**Comment by dwemhoen** [comment]
figured out the problem - I had put quotes around the label. Entering in the label without quotes worked normally.

**Comment by mzarozinski** [comment]
when I use quotes, it just strips them off. Previous fixes appear to have resolved David's issue.
