### ISSUE TITLE
restrict duplication of a label value with different rates

### ISSUE THREAD

**Issue by najin** [CIIR/Proteus#29]
I labeled several papers with the same type:value (arabic:stemming) each with a different rate (1,3, and 4), this resulted in having "stemming" leaf node one for each rate. I suggest either unifying all as one node, or adding the rate to the value in some fashion (i.e. as a number, color, stars,etc)

**Comment by mzarozinski** [comment]
fixed in commit: 7e72eacf8aaff8dc67bfabb6560f500bf726a4d2
