### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by weize** [CIIR/Proteus#31]
Rating window position fixed. this is a problem if I re-size the window.
Unable to delete or edit tags
Duplicate tags in the tag panel
I want to cancel adding rating for a label, but I cannot close the label rating window once it is there.
Not sure if we need a rating for "non-relevant"

**Comment by mzarozinski** [comment]
was able to reproduce duplicate tags - happens when the same tag has different ratings

**Comment by jjfiv** [comment]
Duplicate tags in the tag panel - is a duplicate of #28
Rating window position fixed. this is a problem if I re-size the window. - is a duplicate of #21 

Other issues have been given their own numbers, closing this one for now.
