### ISSUE TITLE
Syntax for phrase search?

### ISSUE THREAD

**Issue by jiepujiang** [CIIR/Proteus#41]
What is the syntax for phrase search? I tried a few such as "click prediction" but no results returned (there should be a lot).

**Comment by mzarozinski** [comment]
Jiepu,

you *should* be able to do just "#od:1(click prediction)" - saying give me an "ordered window within 1 word" but there's a bug in galago. Try this: #dirichlet(#od:1(click prediction))

**Comment by jiepujiang** [comment]
Thanks michael, but it would be painful to write galago queries. It would be nice if you can write a simple query parser supporting Google's query syntax.

**Comment by mzarozinski** [comment]
There actually is a way to do it if you launch galago with the parameter  "--queryType=simple"

**Comment by j-allan** [comment]
I'd call this a bug. We should not be requiring Galago's internal 
syntax!!!! Could we change the semantics of this bug report to be: make 
it possible for someone to use quotation marks to mean a phrase....

                         -- james

**Comment by mzarozinski** [comment]
simple query language is now supported in both galago and proteus.
