### ISSUE TITLE
Dropdown list of labels delayed

### ISSUE THREAD

**Issue by j-allan** [CIIR/Proteus#51]
When I first log in, I don't get my list of labels. Feels like I should, because I may want to work only within one of them.

After I enter my first query, I still don't get the labels. If I refresh at that point, they appear. It seems like they ought to be showing up earlier.

**Comment by jjfiv** [comment]
+1, if we need to trigger a refresh on login, we should.

**Comment by mzarozinski** [comment]
fixed in commit https://github.com/CIIR/Proteus/commit/5d255a5dbed23b5aa3612112bf24d2def0c7ab34
