### ISSUE TITLE
Viewing a document with the default renderer clashes with tags

### ISSUE THREAD

**Issue by jjfiv** [CIIR/Proteus#69]
This is key for its use on new datasets, but not for ACM or Internet Archive, where the link is external, although view links might be useful for debugging.

**Comment by mzarozinski** [comment]
addressed in commit https://github.com/CIIR/Proteus/commit/79e267c3a5a8ab7eab8862de54a909aad67ac4ad

currently opens the doc in a new tab in the proteus interface.  we may want to open it in "blank" tab in the future.
